// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
`

type CreateArtifactParams struct {
	RunID         pgtype.UUID `json:"run_id"`
	Kind          string      `json:"kind"`
	Mime          string      `json:"mime"`
	Size          int64       `json:"size"`
	Sha256        string      `json:"sha256"`
	SchemaVersion string      `json:"schema_version"`
	ParserVersion string      `json:"parser_version"`
	Sensitivity   string      `json:"sensitivity"`
	StorageKey    string      `json:"storage_key"`
	RelType       string      `json:"rel_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.RunID,
		arg.Kind,
		arg.Mime,
		arg.Size,
		arg.Sha256,
		arg.SchemaVersion,
		arg.ParserVersion,
		arg.Sensitivity,
		arg.StorageKey,
		arg.RelType,
		arg.ParentID,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.SchemaVersion,
		&i.ParserVersion,
		&i.Sensitivity,
		&i.StorageKey,
		&i.RelType,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.SchemaVersion,
		&i.ParserVersion,
		&i.Sensitivity,
		&i.StorageKey,
		&i.RelType,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
FROM artifacts
WHERE sha256 = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Content-addressed lookup. Identical bytes can legitimately appear in several
// runs, so this is deterministic newest-first (created_at then id) rather than
// an unordered LIMIT 1.
func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySHA256, sha256)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.SchemaVersion,
		&i.ParserVersion,
		&i.Sensitivity,
		&i.StorageKey,
		&i.RelType,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256InRun = `-- name: GetArtifactBySHA256InRun :one
SELECT id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
FROM artifacts
WHERE run_id = $1 AND sha256 = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetArtifactBySHA256InRunParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Sha256 string      `json:"sha256"`
}

// Run-qualified content lookup: returns the newest artifact with the checksum
// inside a specific run, so a call site that already knows the run gets an
// unambiguous answer even when the same bytes recur across other runs.
func (q *Queries) GetArtifactBySHA256InRun(ctx context.Context, arg GetArtifactBySHA256InRunParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySHA256InRun, arg.RunID, arg.Sha256)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.SchemaVersion,
		&i.ParserVersion,
		&i.Sensitivity,
		&i.StorageKey,
		&i.RelType,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByRun = `-- name: ListArtifactsByRun :many
SELECT id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
FROM artifacts
WHERE run_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Mime,
			&i.Size,
			&i.Sha256,
			&i.SchemaVersion,
			&i.ParserVersion,
			&i.Sensitivity,
			&i.StorageKey,
			&i.RelType,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDerivedArtifacts = `-- name: ListDerivedArtifacts :many
SELECT id, run_id, kind, mime, size, sha256, schema_version, parser_version, sensitivity, storage_key, rel_type, parent_id, created_at
FROM artifacts
WHERE parent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDerivedArtifacts(ctx context.Context, parentID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listDerivedArtifacts, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Mime,
			&i.Size,
			&i.Sha256,
			&i.SchemaVersion,
			&i.ParserVersion,
			&i.Sensitivity,
			&i.StorageKey,
			&i.RelType,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
