// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error)
	// Content-addressed lookup. Identical bytes can legitimately appear in several
	// runs, so this is deterministic newest-first (created_at then id) rather than
	// an unordered LIMIT 1.
	GetArtifactBySHA256(ctx context.Context, sha256 string) (Artifact, error)
	// Run-qualified content lookup: returns the newest artifact with the checksum
	// inside a specific run, so a call site that already knows the run gets an
	// unambiguous answer even when the same bytes recur across other runs.
	GetArtifactBySHA256InRun(ctx context.Context, arg GetArtifactBySHA256InRunParams) (Artifact, error)
	ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]Artifact, error)
	ListDerivedArtifacts(ctx context.Context, parentID pgtype.UUID) ([]Artifact, error)
}

var _ Querier = (*Queries)(nil)
