// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Agent instance lifecycle. Owner: engine/runs. Profile is a role description, not a principal.
type AgentInstance struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Profile   string             `json:"profile"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Approval struct {
	ID        pgtype.UUID        `json:"id"`
	Subject   string             `json:"subject"`
	ScopeID   pgtype.UUID        `json:"scope_id"`
	Action    string             `json:"action"`
	Status    string             `json:"status"`
	DecidedBy pgtype.Text        `json:"decided_by"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Artifact metadata and provenance. Owner: workspace/evidence. Bytes live in the storage adapter; this table holds metadata.
type Artifact struct {
	ID            pgtype.UUID        `json:"id"`
	RunID         pgtype.UUID        `json:"run_id"`
	Kind          string             `json:"kind"`
	Mime          string             `json:"mime"`
	Size          int64              `json:"size"`
	Sha256        string             `json:"sha256"`
	SchemaVersion string             `json:"schema_version"`
	ParserVersion string             `json:"parser_version"`
	Sensitivity   string             `json:"sensitivity"`
	StorageKey    string             `json:"storage_key"`
	RelType       string             `json:"rel_type"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Attack-surface asset. Owner: workspace/assessment. Model must extend beyond URL/HTTP.
type Asset struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      pgtype.UUID        `json:"run_id"`
	Kind       string             `json:"kind"`
	Name       string             `json:"name"`
	Properties []byte             `json:"properties"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Business audit history, distinct from application telemetry. Owner: platform/audit.
type AuditRecord struct {
	ID          pgtype.UUID        `json:"id"`
	Actor       string             `json:"actor"`
	Action      string             `json:"action"`
	Resource    string             `json:"resource"`
	Outcome     string             `json:"outcome"`
	Reason      string             `json:"reason"`
	Correlation string             `json:"correlation"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Capability grants. Owner: platform/governance. Grant is checked against current scope at dispatch time; snapshot does not override later revocation.
type CapabilityGrant struct {
	ID         pgtype.UUID        `json:"id"`
	Subject    string             `json:"subject"`
	ScopeID    pgtype.UUID        `json:"scope_id"`
	Capability string             `json:"capability"`
	GrantedBy  string             `json:"granted_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Track what was checked, method, outcome, limits. Owner: workspace/assessment. budget_exhausted should not mark as verified.
type CoverageEntry struct {
	ID           pgtype.UUID        `json:"id"`
	RunID        pgtype.UUID        `json:"run_id"`
	HypothesisID pgtype.UUID        `json:"hypothesis_id"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	Method       string             `json:"method"`
	Outcome      string             `json:"outcome"`
	EvidenceID   pgtype.UUID        `json:"evidence_id"`
	Reason       string             `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Finding aggregate. Owner: workspace/findings (only owner of status transition).
type Finding struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	Confidence  string             `json:"confidence"`
	Status      string             `json:"status"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FindingEvidence struct {
	FindingID  pgtype.UUID `json:"finding_id"`
	EvidenceID pgtype.UUID `json:"evidence_id"`
	Role       string      `json:"role"`
}

// Review history for status transitions. Owner: workspace/findings.
type FindingReviewHistory struct {
	ID         pgtype.UUID        `json:"id"`
	FindingID  pgtype.UUID        `json:"finding_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Reviewer   string             `json:"reviewer"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Verifier output. Owner: workspace/findings records it; verifier must not flip finding.status directly.
type FindingVerdict struct {
	ID         pgtype.UUID        `json:"id"`
	FindingID  pgtype.UUID        `json:"finding_id"`
	Verdict    string             `json:"verdict"`
	Reason     string             `json:"reason"`
	ProducedBy string             `json:"produced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Hypothesis struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Observed response/behavior. Owner: workspace/assessment. Accepted observations live here, not in evidence.
type Observation struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      pgtype.UUID        `json:"run_id"`
	AssetID    pgtype.UUID        `json:"asset_id"`
	Summary    string             `json:"summary"`
	Detail     string             `json:"detail"`
	EvidenceID pgtype.UUID        `json:"evidence_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Comment string      `json:"comment"`
}

// Project metadata and lifecycle. Owner: platform/projects.
type Project struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ScopeVersion int32              `json:"scope_version"`
}

// Project membership. Owner: platform/projects. Persona/agent role does not grant membership here.
type ProjectMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Subject   string             `json:"subject"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

// Run lifecycle. Owner: engine/runs. budget_exhausted is distinct from completed.
type Run struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedBy string             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Versioned engagement scope. Owner: platform/projects. New assets do not auto-extend scope.
type Scope struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Version      int32              `json:"version"`
	AssetTypes   []string           `json:"asset_types"`
	Include      []string           `json:"include"`
	Exclude      []string           `json:"exclude"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ApprovalNote pgtype.Text        `json:"approval_note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Dependency graph independent of agent tree. Owner: engine/runs.
type TaskDependency struct {
	TaskID    pgtype.UUID `json:"task_id"`
	DependsOn pgtype.UUID `json:"depends_on"`
	Required  bool        `json:"required"`
}
