// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (project_id, subject, role)
VALUES ($1, $2, $3)
RETURNING project_id, subject, role, created_at
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Subject   string      `json:"subject"`
	Role      string      `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.Subject, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.Subject,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, status)
VALUES ($1, $2, 'active')
RETURNING id, name, slug, status, created_at, updated_at, scope_version
`

type CreateProjectParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeVersion,
	)
	return i, err
}

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (project_id, version, asset_types, include, exclude, expires_at, approval_note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, version, asset_types, include, exclude, expires_at, approval_note, created_at
`

type CreateScopeParams struct {
	ProjectID    pgtype.UUID        `json:"project_id"`
	Version      int32              `json:"version"`
	AssetTypes   []string           `json:"asset_types"`
	Include      []string           `json:"include"`
	Exclude      []string           `json:"exclude"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ApprovalNote pgtype.Text        `json:"approval_note"`
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, createScope,
		arg.ProjectID,
		arg.Version,
		arg.AssetTypes,
		arg.Include,
		arg.Exclude,
		arg.ExpiresAt,
		arg.ApprovalNote,
	)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.AssetTypes,
		&i.Include,
		&i.Exclude,
		&i.ExpiresAt,
		&i.ApprovalNote,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role
FROM project_members
WHERE project_id = $1 AND subject = $2
`

type GetMemberRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Subject   string      `json:"subject"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.ProjectID, arg.Subject)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, slug, status, created_at, updated_at, scope_version
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeVersion,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, status, created_at, updated_at, scope_version
FROM projects
WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeVersion,
	)
	return i, err
}

const getScopeByID = `-- name: GetScopeByID :one
SELECT id, project_id, version, asset_types, include, exclude, expires_at, approval_note, created_at
FROM scopes
WHERE id = $1
`

func (q *Queries) GetScopeByID(ctx context.Context, id pgtype.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, getScopeByID, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.AssetTypes,
		&i.Include,
		&i.Exclude,
		&i.ExpiresAt,
		&i.ApprovalNote,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT project_id, subject, role, created_at
FROM project_members
WHERE project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.Subject,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, status, created_at, updated_at, scope_version
FROM projects
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScopeVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopesByProject = `-- name: ListScopesByProject :many
SELECT id, project_id, version, asset_types, include, exclude, expires_at, approval_note, created_at
FROM scopes
WHERE project_id = $1
ORDER BY version DESC
`

func (q *Queries) ListScopesByProject(ctx context.Context, projectID pgtype.UUID) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listScopesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.AssetTypes,
			&i.Include,
			&i.Exclude,
			&i.ExpiresAt,
			&i.ApprovalNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextScopeVersion = `-- name: NextScopeVersion :one
UPDATE projects
SET scope_version = scope_version + 1
WHERE projects.id = $1
RETURNING scope_version
`

// Atomically reserves the next project-local scope version. The UPDATE takes a
// row lock on the project and, under READ COMMITTED, re-reads the row after any
// concurrent lock wait, so two callers always receive distinct values. A
// version may be skipped if the following insert fails, which is acceptable.
func (q *Queries) NextScopeVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextScopeVersion, id)
	var scope_version int32
	err := row.Scan(&scope_version)
	return scope_version, err
}

const setProjectStatus = `-- name: SetProjectStatus :one
UPDATE projects
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, scope_version
`

type SetProjectStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetProjectStatus(ctx context.Context, arg SetProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectStatus, arg.ID, arg.Status)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeVersion,
	)
	return i, err
}
