// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetScopeByID(ctx context.Context, id pgtype.UUID) (Scope, error)
	ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListScopesByProject(ctx context.Context, projectID pgtype.UUID) ([]Scope, error)
	// Atomically reserves the next project-local scope version. The UPDATE takes a
	// row lock on the project and, under READ COMMITTED, re-reads the row after any
	// concurrent lock wait, so two callers always receive distinct values. A
	// version may be skipped if the following insert fails, which is acceptable.
	NextScopeVersion(ctx context.Context, id pgtype.UUID) (int32, error)
	SetProjectStatus(ctx context.Context, arg SetProjectStatusParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
