// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (subject, scope_id, action, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, subject, scope_id, action, status, decided_by, decided_at, reason, created_at, expires_at
`

type CreateApprovalParams struct {
	Subject   string             `json:"subject"`
	ScopeID   pgtype.UUID        `json:"scope_id"`
	Action    string             `json:"action"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.Subject,
		arg.ScopeID,
		arg.Action,
		arg.ExpiresAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Action,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createCapabilityGrant = `-- name: CreateCapabilityGrant :one
INSERT INTO capability_grants (subject, scope_id, capability, granted_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subject, scope_id, capability, granted_by, created_at, revoked_at, expires_at
`

type CreateCapabilityGrantParams struct {
	Subject    string             `json:"subject"`
	ScopeID    pgtype.UUID        `json:"scope_id"`
	Capability string             `json:"capability"`
	GrantedBy  string             `json:"granted_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCapabilityGrant(ctx context.Context, arg CreateCapabilityGrantParams) (CapabilityGrant, error) {
	row := q.db.QueryRow(ctx, createCapabilityGrant,
		arg.Subject,
		arg.ScopeID,
		arg.Capability,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i CapabilityGrant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Capability,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (name, comment)
VALUES ($1, $2)
RETURNING id, name, comment
`

type CreatePermissionParams struct {
	Name    string `json:"name"`
	Comment string `json:"comment"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Comment)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Comment)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals
SET status = $2, decided_by = $3, decided_at = now(), reason = $4
WHERE id = $1 AND status = 'pending'
RETURNING id, subject, scope_id, action, status, decided_by, decided_at, reason, created_at, expires_at
`

type DecideApprovalParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	DecidedBy pgtype.Text `json:"decided_by"`
	Reason    string      `json:"reason"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.Reason,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Action,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, subject, scope_id, action, status, decided_by, decided_at, reason, created_at, expires_at
FROM approvals
WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id pgtype.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Action,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCapabilityGrant = `-- name: GetCapabilityGrant :one
SELECT id, subject, scope_id, capability, granted_by, created_at, revoked_at, expires_at
FROM capability_grants
WHERE id = $1
`

func (q *Queries) GetCapabilityGrant(ctx context.Context, id pgtype.UUID) (CapabilityGrant, error) {
	row := q.db.QueryRow(ctx, getCapabilityGrant, id)
	var i CapabilityGrant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Capability,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPermission = `-- name: GetPermission :one
SELECT id, name, comment FROM permissions WHERE name = $1
`

func (q *Queries) GetPermission(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Comment)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const grantRolePermission = `-- name: GrantRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
`

type GrantRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error {
	_, err := q.db.Exec(ctx, grantRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const listActiveGrantsForSubjectScope = `-- name: ListActiveGrantsForSubjectScope :many
SELECT id, subject, scope_id, capability, granted_by, created_at, revoked_at, expires_at
FROM capability_grants
WHERE subject = $1
  AND scope_id = $2
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at
`

type ListActiveGrantsForSubjectScopeParams struct {
	Subject string      `json:"subject"`
	ScopeID pgtype.UUID `json:"scope_id"`
}

func (q *Queries) ListActiveGrantsForSubjectScope(ctx context.Context, arg ListActiveGrantsForSubjectScopeParams) ([]CapabilityGrant, error) {
	rows, err := q.db.Query(ctx, listActiveGrantsForSubjectScope, arg.Subject, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityGrant
	for rows.Next() {
		var i CapabilityGrant
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.ScopeID,
			&i.Capability,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCapabilityGrant = `-- name: RevokeCapabilityGrant :one
UPDATE capability_grants
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
RETURNING id, subject, scope_id, capability, granted_by, created_at, revoked_at, expires_at
`

// Idempotent: revoking an already-revoked grant returns the row unchanged so
// callers can tell "already revoked" from "does not exist" (ErrNoRows).
func (q *Queries) RevokeCapabilityGrant(ctx context.Context, id pgtype.UUID) (CapabilityGrant, error) {
	row := q.db.QueryRow(ctx, revokeCapabilityGrant, id)
	var i CapabilityGrant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.ScopeID,
		&i.Capability,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const roleHasPermission = `-- name: RoleHasPermission :one
SELECT count(*) FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RoleHasPermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, roleHasPermission, arg.RoleID, arg.PermissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
