// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error)
	CreateCapabilityGrant(ctx context.Context, arg CreateCapabilityGrantParams) (CapabilityGrant, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error)
	GetApproval(ctx context.Context, id pgtype.UUID) (Approval, error)
	GetCapabilityGrant(ctx context.Context, id pgtype.UUID) (CapabilityGrant, error)
	GetPermission(ctx context.Context, name string) (Permission, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error
	ListActiveGrantsForSubjectScope(ctx context.Context, arg ListActiveGrantsForSubjectScopeParams) ([]CapabilityGrant, error)
	// Idempotent: revoking an already-revoked grant returns the row unchanged so
	// callers can tell "already revoked" from "does not exist" (ErrNoRows).
	RevokeCapabilityGrant(ctx context.Context, id pgtype.UUID) (CapabilityGrant, error)
	RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
