// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditRecord = `-- name: GetAuditRecord :one
SELECT id, actor, action, resource, outcome, reason, correlation, created_at
FROM audit_records
WHERE id = $1
`

func (q *Queries) GetAuditRecord(ctx context.Context, id pgtype.UUID) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, getAuditRecord, id)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.Resource,
		&i.Outcome,
		&i.Reason,
		&i.Correlation,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditRecord = `-- name: InsertAuditRecord :one
INSERT INTO audit_records (actor, action, resource, outcome, reason, correlation)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor, action, resource, outcome, reason, correlation, created_at
`

type InsertAuditRecordParams struct {
	Actor       string `json:"actor"`
	Action      string `json:"action"`
	Resource    string `json:"resource"`
	Outcome     string `json:"outcome"`
	Reason      string `json:"reason"`
	Correlation string `json:"correlation"`
}

func (q *Queries) InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, insertAuditRecord,
		arg.Actor,
		arg.Action,
		arg.Resource,
		arg.Outcome,
		arg.Reason,
		arg.Correlation,
	)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.Resource,
		&i.Outcome,
		&i.Reason,
		&i.Correlation,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByActor = `-- name: ListAuditByActor :many
SELECT id, actor, action, resource, outcome, reason, correlation, created_at
FROM audit_records
WHERE actor = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditByActor(ctx context.Context, actor string) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, listAuditByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRecord
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.Reason,
			&i.Correlation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByCorrelation = `-- name: ListAuditByCorrelation :many
SELECT id, actor, action, resource, outcome, reason, correlation, created_at
FROM audit_records
WHERE correlation = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditByCorrelation(ctx context.Context, correlation string) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, listAuditByCorrelation, correlation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRecord
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.Reason,
			&i.Correlation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
