// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAuditRecord(ctx context.Context, id pgtype.UUID) (AuditRecord, error)
	InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) (AuditRecord, error)
	ListAuditByActor(ctx context.Context, actor string) ([]AuditRecord, error)
	ListAuditByCorrelation(ctx context.Context, correlation string) ([]AuditRecord, error)
}

var _ Querier = (*Queries)(nil)
