// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO agent_messages (attempt_id, seq, role, content, invocation_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, attempt_id, seq, role, content, invocation_id, created_at
`

type AppendMessageParams struct {
	AttemptID    pgtype.UUID `json:"attempt_id"`
	Seq          int32       `json:"seq"`
	Role         string      `json:"role"`
	Content      string      `json:"content"`
	InvocationID pgtype.UUID `json:"invocation_id"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (AgentMessage, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.AttemptID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.InvocationID,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.InvocationID,
		&i.CreatedAt,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO agent_attempts (agent_id, attempt_no, status, started_at)
VALUES (
    $1,
    COALESCE((SELECT MAX(attempt_no) FROM agent_attempts WHERE agent_id = $1), 0) + 1,
    'running',
    now()
)
RETURNING id, agent_id, attempt_no, status, request_key, request_fingerprint, started_at, finished_at, created_at, updated_at
`

type CreateAttemptRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	AttemptNo          int32              `json:"attempt_no"`
	Status             string             `json:"status"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, agentID pgtype.UUID) (CreateAttemptRow, error) {
	row := q.db.QueryRow(ctx, createAttempt, agentID)
	var i CreateAttemptRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AttemptNo,
		&i.Status,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrGetAttempt = `-- name: CreateOrGetAttempt :one
INSERT INTO agent_attempts (agent_id, attempt_no, status, started_at, request_key, request_fingerprint)
VALUES (
    $1,
    COALESCE((SELECT MAX(attempt_no) FROM agent_attempts WHERE agent_id = $1), 0) + 1,
    'running',
    now(),
    $2,
    $3
)
ON CONFLICT (agent_id, request_key) WHERE request_key <> ''
DO UPDATE SET request_key = EXCLUDED.request_key
RETURNING id, agent_id, attempt_no, status, request_key, request_fingerprint, started_at, finished_at, created_at, updated_at, (xmax = 0) AS created
`

type CreateOrGetAttemptParams struct {
	AgentID            pgtype.UUID `json:"agent_id"`
	RequestKey         string      `json:"request_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
}

type CreateOrGetAttemptRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	AttemptNo          int32              `json:"attempt_no"`
	Status             string             `json:"status"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Created            bool               `json:"created"`
}

func (q *Queries) CreateOrGetAttempt(ctx context.Context, arg CreateOrGetAttemptParams) (CreateOrGetAttemptRow, error) {
	row := q.db.QueryRow(ctx, createOrGetAttempt, arg.AgentID, arg.RequestKey, arg.RequestFingerprint)
	var i CreateOrGetAttemptRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AttemptNo,
		&i.Status,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO agent_snapshots (agent_id, profile_ref, content_hash, requested, granted)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (agent_id, content_hash)
DO UPDATE SET profile_ref = EXCLUDED.profile_ref
RETURNING id, agent_id, profile_ref, content_hash, requested, granted, created_at
`

type CreateSnapshotParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	ProfileRef  string      `json:"profile_ref"`
	ContentHash string      `json:"content_hash"`
	Requested   []byte      `json:"requested"`
	Granted     []byte      `json:"granted"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (AgentSnapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.AgentID,
		arg.ProfileRef,
		arg.ContentHash,
		arg.Requested,
		arg.Granted,
	)
	var i AgentSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ProfileRef,
		&i.ContentHash,
		&i.Requested,
		&i.Granted,
		&i.CreatedAt,
	)
	return i, err
}

const finishAttempt = `-- name: FinishAttempt :one
UPDATE agent_attempts
SET status = $2,
    finished_at = $3,
    updated_at = now()
WHERE id = $1
  AND status = 'running'
RETURNING id, agent_id, attempt_no, status, request_key, request_fingerprint, started_at, finished_at, created_at, updated_at
`

type FinishAttemptParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type FinishAttemptRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	AttemptNo          int32              `json:"attempt_no"`
	Status             string             `json:"status"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (FinishAttemptRow, error) {
	row := q.db.QueryRow(ctx, finishAttempt, arg.ID, arg.Status, arg.FinishedAt)
	var i FinishAttemptRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AttemptNo,
		&i.Status,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, agent_id, attempt_no, status, request_key, request_fingerprint, started_at, finished_at, created_at, updated_at
FROM agent_attempts
WHERE id = $1
`

type GetAttemptRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	AttemptNo          int32              `json:"attempt_no"`
	Status             string             `json:"status"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAttempt(ctx context.Context, id pgtype.UUID) (GetAttemptRow, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i GetAttemptRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AttemptNo,
		&i.Status,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnapshotByAgent = `-- name: GetSnapshotByAgent :one
SELECT id, agent_id, profile_ref, content_hash, requested, granted, created_at
FROM agent_snapshots
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSnapshotByAgent(ctx context.Context, agentID pgtype.UUID) (AgentSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByAgent, agentID)
	var i AgentSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ProfileRef,
		&i.ContentHash,
		&i.Requested,
		&i.Granted,
		&i.CreatedAt,
	)
	return i, err
}

const listAttemptsByAgent = `-- name: ListAttemptsByAgent :many
SELECT id, agent_id, attempt_no, status, request_key, request_fingerprint, started_at, finished_at, created_at, updated_at
FROM agent_attempts
WHERE agent_id = $1
ORDER BY attempt_no DESC
`

type ListAttemptsByAgentRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	AttemptNo          int32              `json:"attempt_no"`
	Status             string             `json:"status"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAttemptsByAgent(ctx context.Context, agentID pgtype.UUID) ([]ListAttemptsByAgentRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsByAgentRow{}
	for rows.Next() {
		var i ListAttemptsByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AttemptNo,
			&i.Status,
			&i.RequestKey,
			&i.RequestFingerprint,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, attempt_id, seq, role, content, invocation_id, created_at
FROM agent_messages
WHERE attempt_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListMessages(ctx context.Context, attemptID pgtype.UUID) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.InvocationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
