// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendMessage(ctx context.Context, arg AppendMessageParams) (AgentMessage, error)
	CreateAttempt(ctx context.Context, agentID pgtype.UUID) (AgentAttempt, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (AgentSnapshot, error)
	FinishAttempt(ctx context.Context, arg FinishAttemptParams) (AgentAttempt, error)
	GetAttempt(ctx context.Context, id pgtype.UUID) (AgentAttempt, error)
	GetSnapshotByAgent(ctx context.Context, agentID pgtype.UUID) (AgentSnapshot, error)
	ListAttemptsByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentAttempt, error)
	ListMessages(ctx context.Context, attemptID pgtype.UUID) ([]AgentMessage, error)
}

var _ Querier = (*Queries)(nil)
