// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invocations.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvocationsByRun = `-- name: CountInvocationsByRun :one
SELECT count(*)
FROM tool_invocations
WHERE run_id = $1
`

func (q *Queries) CountInvocationsByRun(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvocationsByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvocation = `-- name: CreateInvocation :one
INSERT INTO tool_invocations (
    run_id, task_id, scope_id, actor, capability, capability_version,
    status, request, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $8)
RETURNING id, run_id, task_id, scope_id, actor, capability, capability_version,
          status, request, raw_artifact_id, structured_artifact_id,
          result_execution, result_parse, exit_code, error_code, error_message,
          idempotency_key, version, started_at, finished_at, created_at, updated_at
`

type CreateInvocationParams struct {
	RunID             pgtype.UUID `json:"run_id"`
	TaskID            pgtype.UUID `json:"task_id"`
	ScopeID           pgtype.UUID `json:"scope_id"`
	Actor             string      `json:"actor"`
	Capability        string      `json:"capability"`
	CapabilityVersion string      `json:"capability_version"`
	Request           []byte      `json:"request"`
	IdempotencyKey    string      `json:"idempotency_key"`
}

func (q *Queries) CreateInvocation(ctx context.Context, arg CreateInvocationParams) (ToolInvocation, error) {
	row := q.db.QueryRow(ctx, createInvocation,
		arg.RunID,
		arg.TaskID,
		arg.ScopeID,
		arg.Actor,
		arg.Capability,
		arg.CapabilityVersion,
		arg.Request,
		arg.IdempotencyKey,
	)
	var i ToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.ScopeID,
		&i.Actor,
		&i.Capability,
		&i.CapabilityVersion,
		&i.Status,
		&i.Request,
		&i.RawArtifactID,
		&i.StructuredArtifactID,
		&i.ResultExecution,
		&i.ResultParse,
		&i.ExitCode,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.Version,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvocation = `-- name: GetInvocation :one
SELECT id, run_id, task_id, scope_id, actor, capability, capability_version,
       status, request, raw_artifact_id, structured_artifact_id,
       result_execution, result_parse, exit_code, error_code, error_message,
       idempotency_key, version, started_at, finished_at, created_at, updated_at
FROM tool_invocations
WHERE id = $1
`

func (q *Queries) GetInvocation(ctx context.Context, id pgtype.UUID) (ToolInvocation, error) {
	row := q.db.QueryRow(ctx, getInvocation, id)
	var i ToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.ScopeID,
		&i.Actor,
		&i.Capability,
		&i.CapabilityVersion,
		&i.Status,
		&i.Request,
		&i.RawArtifactID,
		&i.StructuredArtifactID,
		&i.ResultExecution,
		&i.ResultParse,
		&i.ExitCode,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.Version,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvocationByRunAndKey = `-- name: GetInvocationByRunAndKey :one
SELECT id, run_id, task_id, scope_id, actor, capability, capability_version,
       status, request, raw_artifact_id, structured_artifact_id,
       result_execution, result_parse, exit_code, error_code, error_message,
       idempotency_key, version, started_at, finished_at, created_at, updated_at
FROM tool_invocations
WHERE run_id = $1 AND idempotency_key = $2
`

type GetInvocationByRunAndKeyParams struct {
	RunID          pgtype.UUID `json:"run_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetInvocationByRunAndKey(ctx context.Context, arg GetInvocationByRunAndKeyParams) (ToolInvocation, error) {
	row := q.db.QueryRow(ctx, getInvocationByRunAndKey, arg.RunID, arg.IdempotencyKey)
	var i ToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.ScopeID,
		&i.Actor,
		&i.Capability,
		&i.CapabilityVersion,
		&i.Status,
		&i.Request,
		&i.RawArtifactID,
		&i.StructuredArtifactID,
		&i.ResultExecution,
		&i.ResultParse,
		&i.ExitCode,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.Version,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvocationsByRun = `-- name: ListInvocationsByRun :many
SELECT id, run_id, task_id, scope_id, actor, capability, capability_version,
       status, request, raw_artifact_id, structured_artifact_id,
       result_execution, result_parse, exit_code, error_code, error_message,
       idempotency_key, version, started_at, finished_at, created_at, updated_at
FROM tool_invocations
WHERE run_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvocationsByRun(ctx context.Context, runID pgtype.UUID) ([]ToolInvocation, error) {
	rows, err := q.db.Query(ctx, listInvocationsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolInvocation{}
	for rows.Next() {
		var i ToolInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TaskID,
			&i.ScopeID,
			&i.Actor,
			&i.Capability,
			&i.CapabilityVersion,
			&i.Status,
			&i.Request,
			&i.RawArtifactID,
			&i.StructuredArtifactID,
			&i.ResultExecution,
			&i.ResultParse,
			&i.ExitCode,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.IdempotencyKey,
			&i.Version,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvocationResult = `-- name: UpdateInvocationResult :one
UPDATE tool_invocations
SET status = $2,
    raw_artifact_id = $3,
    structured_artifact_id = $4,
    result_execution = $5,
    result_parse = $6,
    exit_code = $7,
    error_code = $8,
    error_message = $9,
    finished_at = $10,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $11
RETURNING id, run_id, task_id, scope_id, actor, capability, capability_version,
          status, request, raw_artifact_id, structured_artifact_id,
          result_execution, result_parse, exit_code, error_code, error_message,
          idempotency_key, version, started_at, finished_at, created_at, updated_at
`

type UpdateInvocationResultParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Status               string             `json:"status"`
	RawArtifactID        pgtype.UUID        `json:"raw_artifact_id"`
	StructuredArtifactID pgtype.UUID        `json:"structured_artifact_id"`
	ResultExecution      string             `json:"result_execution"`
	ResultParse          string             `json:"result_parse"`
	ExitCode             pgtype.Int4        `json:"exit_code"`
	ErrorCode            string             `json:"error_code"`
	ErrorMessage         string             `json:"error_message"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	Version              int32              `json:"version"`
}

func (q *Queries) UpdateInvocationResult(ctx context.Context, arg UpdateInvocationResultParams) (ToolInvocation, error) {
	row := q.db.QueryRow(ctx, updateInvocationResult,
		arg.ID,
		arg.Status,
		arg.RawArtifactID,
		arg.StructuredArtifactID,
		arg.ResultExecution,
		arg.ResultParse,
		arg.ExitCode,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.Version,
	)
	var i ToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.ScopeID,
		&i.Actor,
		&i.Capability,
		&i.CapabilityVersion,
		&i.Status,
		&i.Request,
		&i.RawArtifactID,
		&i.StructuredArtifactID,
		&i.ResultExecution,
		&i.ResultParse,
		&i.ExitCode,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.Version,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
