// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (run_id, kind, name, properties)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, kind, name, properties, created_at
`

type CreateAssetParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	Kind       string      `json:"kind"`
	Name       string      `json:"name"`
	Properties []byte      `json:"properties"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.RunID,
		arg.Kind,
		arg.Name,
		arg.Properties,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Name,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const createCoverageEntry = `-- name: CreateCoverageEntry :one
INSERT INTO coverage_entries (run_id, hypothesis_id, asset_id, method, outcome, evidence_id, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, run_id, hypothesis_id, asset_id, method, outcome, evidence_id, reason, created_at
`

type CreateCoverageEntryParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	HypothesisID pgtype.UUID `json:"hypothesis_id"`
	AssetID      pgtype.UUID `json:"asset_id"`
	Method       string      `json:"method"`
	Outcome      string      `json:"outcome"`
	EvidenceID   pgtype.UUID `json:"evidence_id"`
	Reason       string      `json:"reason"`
}

func (q *Queries) CreateCoverageEntry(ctx context.Context, arg CreateCoverageEntryParams) (CoverageEntry, error) {
	row := q.db.QueryRow(ctx, createCoverageEntry,
		arg.RunID,
		arg.HypothesisID,
		arg.AssetID,
		arg.Method,
		arg.Outcome,
		arg.EvidenceID,
		arg.Reason,
	)
	var i CoverageEntry
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.HypothesisID,
		&i.AssetID,
		&i.Method,
		&i.Outcome,
		&i.EvidenceID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createHypothesis = `-- name: CreateHypothesis :one
INSERT INTO hypotheses (run_id, title, description, status)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, title, description, status, created_at
`

type CreateHypothesisParams struct {
	RunID       pgtype.UUID `json:"run_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateHypothesis(ctx context.Context, arg CreateHypothesisParams) (Hypothesis, error) {
	row := q.db.QueryRow(ctx, createHypothesis,
		arg.RunID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Hypothesis
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (run_id, asset_id, summary, detail, evidence_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, asset_id, summary, detail, evidence_id, created_at
`

type CreateObservationParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	AssetID    pgtype.UUID `json:"asset_id"`
	Summary    string      `json:"summary"`
	Detail     string      `json:"detail"`
	EvidenceID pgtype.UUID `json:"evidence_id"`
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.RunID,
		arg.AssetID,
		arg.Summary,
		arg.Detail,
		arg.EvidenceID,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AssetID,
		&i.Summary,
		&i.Detail,
		&i.EvidenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, run_id, kind, name, properties, created_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Name,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const getCoverageEntry = `-- name: GetCoverageEntry :one
SELECT id, run_id, hypothesis_id, asset_id, method, outcome, evidence_id, reason, created_at
FROM coverage_entries
WHERE id = $1
`

func (q *Queries) GetCoverageEntry(ctx context.Context, id pgtype.UUID) (CoverageEntry, error) {
	row := q.db.QueryRow(ctx, getCoverageEntry, id)
	var i CoverageEntry
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.HypothesisID,
		&i.AssetID,
		&i.Method,
		&i.Outcome,
		&i.EvidenceID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getHypothesis = `-- name: GetHypothesis :one
SELECT id, run_id, title, description, status, created_at
FROM hypotheses
WHERE id = $1
`

func (q *Queries) GetHypothesis(ctx context.Context, id pgtype.UUID) (Hypothesis, error) {
	row := q.db.QueryRow(ctx, getHypothesis, id)
	var i Hypothesis
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getObservation = `-- name: GetObservation :one
SELECT id, run_id, asset_id, summary, detail, evidence_id, created_at
FROM observations
WHERE id = $1
`

func (q *Queries) GetObservation(ctx context.Context, id pgtype.UUID) (Observation, error) {
	row := q.db.QueryRow(ctx, getObservation, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AssetID,
		&i.Summary,
		&i.Detail,
		&i.EvidenceID,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByRun = `-- name: ListAssetsByRun :many
SELECT id, run_id, kind, name, properties, created_at
FROM assets
WHERE run_id = $1
ORDER BY created_at
`

func (q *Queries) ListAssetsByRun(ctx context.Context, runID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Name,
			&i.Properties,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverageByRun = `-- name: ListCoverageByRun :many
SELECT id, run_id, hypothesis_id, asset_id, method, outcome, evidence_id, reason, created_at
FROM coverage_entries
WHERE run_id = $1
ORDER BY created_at
`

func (q *Queries) ListCoverageByRun(ctx context.Context, runID pgtype.UUID) ([]CoverageEntry, error) {
	rows, err := q.db.Query(ctx, listCoverageByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoverageEntry
	for rows.Next() {
		var i CoverageEntry
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.HypothesisID,
			&i.AssetID,
			&i.Method,
			&i.Outcome,
			&i.EvidenceID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByRun = `-- name: ListObservationsByRun :many
SELECT id, run_id, asset_id, summary, detail, evidence_id, created_at
FROM observations
WHERE run_id = $1
ORDER BY created_at
`

func (q *Queries) ListObservationsByRun(ctx context.Context, runID pgtype.UUID) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AssetID,
			&i.Summary,
			&i.Detail,
			&i.EvidenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHypothesisStatus = `-- name: UpdateHypothesisStatus :one
UPDATE hypotheses
SET status = $2
WHERE id = $1
RETURNING id, run_id, title, description, status, created_at
`

type UpdateHypothesisStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateHypothesisStatus(ctx context.Context, arg UpdateHypothesisStatusParams) (Hypothesis, error) {
	row := q.db.QueryRow(ctx, updateHypothesisStatus, arg.ID, arg.Status)
	var i Hypothesis
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
