// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateCoverageEntry(ctx context.Context, arg CreateCoverageEntryParams) (CoverageEntry, error)
	CreateHypothesis(ctx context.Context, arg CreateHypothesisParams) (Hypothesis, error)
	CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error)
	GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error)
	GetCoverageEntry(ctx context.Context, id pgtype.UUID) (CoverageEntry, error)
	GetHypothesis(ctx context.Context, id pgtype.UUID) (Hypothesis, error)
	GetObservation(ctx context.Context, id pgtype.UUID) (Observation, error)
	ListAssetsByRun(ctx context.Context, runID pgtype.UUID) ([]Asset, error)
	ListCoverageByRun(ctx context.Context, runID pgtype.UUID) ([]CoverageEntry, error)
	ListObservationsByRun(ctx context.Context, runID pgtype.UUID) ([]Observation, error)
	UpdateHypothesisStatus(ctx context.Context, arg UpdateHypothesisStatusParams) (Hypothesis, error)
}

var _ Querier = (*Queries)(nil)
