// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	CreateAgentInstance(ctx context.Context, arg CreateAgentInstanceParams) (AgentInstance, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetAgentInstance(ctx context.Context, id pgtype.UUID) (AgentInstance, error)
	GetRun(ctx context.Context, id pgtype.UUID) (Run, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	ListAgentInstancesByRun(ctx context.Context, runID pgtype.UUID) ([]AgentInstance, error)
	ListRunsByProject(ctx context.Context, projectID pgtype.UUID) ([]Run, error)
	ListTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]TaskDependency, error)
	ListTasksByRun(ctx context.Context, runID pgtype.UUID) ([]Task, error)
	TransitionAgentInstance(ctx context.Context, arg TransitionAgentInstanceParams) (AgentInstance, error)
	TransitionRun(ctx context.Context, arg TransitionRunParams) (Run, error)
	TransitionTask(ctx context.Context, arg TransitionTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
