// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on, required)
VALUES ($1, $2, $3)
`

type AddTaskDependencyParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	DependsOn pgtype.UUID `json:"depends_on"`
	Required  bool        `json:"required"`
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, addTaskDependency, arg.TaskID, arg.DependsOn, arg.Required)
	return err
}

const createAgentInstance = `-- name: CreateAgentInstance :one
INSERT INTO agent_instances (run_id, task_id, profile, status)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, task_id, profile, status, version, created_at, updated_at
`

type CreateAgentInstanceParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	TaskID  pgtype.UUID `json:"task_id"`
	Profile string      `json:"profile"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateAgentInstance(ctx context.Context, arg CreateAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, createAgentInstance,
		arg.RunID,
		arg.TaskID,
		arg.Profile,
		arg.Status,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, name, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, status, version, created_by, created_at, updated_at
`

type CreateRunParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Status    string      `json:"status"`
	CreatedBy string      `json:"created_by"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (run_id, name, status)
VALUES ($1, $2, $3)
RETURNING id, run_id, name, status, version, created_at, updated_at
`

type CreateTaskParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Name   string      `json:"name"`
	Status string      `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.RunID, arg.Name, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentInstance = `-- name: GetAgentInstance :one
SELECT id, run_id, task_id, profile, status, version, created_at, updated_at
FROM agent_instances
WHERE id = $1
`

func (q *Queries) GetAgentInstance(ctx context.Context, id pgtype.UUID) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstance, id)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, name, status, version, created_by, created_at, updated_at
FROM runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, run_id, name, status, version, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentInstancesByRun = `-- name: ListAgentInstancesByRun :many
SELECT id, run_id, task_id, profile, status, version, created_at, updated_at
FROM agent_instances
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentInstancesByRun(ctx context.Context, runID pgtype.UUID) ([]AgentInstance, error) {
	rows, err := q.db.Query(ctx, listAgentInstancesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstance
	for rows.Next() {
		var i AgentInstance
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TaskID,
			&i.Profile,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, name, status, version, created_by, created_at, updated_at
FROM runs
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRunsByProject(ctx context.Context, projectID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependencies = `-- name: ListTaskDependencies :many
SELECT task_id, depends_on, required
FROM task_dependencies
WHERE task_id = $1
`

func (q *Queries) ListTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDependency
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(&i.TaskID, &i.DependsOn, &i.Required); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionAgentInstance = `-- name: TransitionAgentInstance :one
UPDATE agent_instances
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, run_id, task_id, profile, status, version, created_at, updated_at
`

type TransitionAgentInstanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

func (q *Queries) TransitionAgentInstance(ctx context.Context, arg TransitionAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, transitionAgentInstance, arg.ID, arg.Status, arg.Version)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionRun = `-- name: TransitionRun :one
UPDATE runs
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, project_id, name, status, version, created_by, created_at, updated_at
`

type TransitionRunParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

func (q *Queries) TransitionRun(ctx context.Context, arg TransitionRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, transitionRun, arg.ID, arg.Status, arg.Version)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionTask = `-- name: TransitionTask :one
UPDATE tasks
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, run_id, name, status, version, created_at, updated_at
`

type TransitionTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

func (q *Queries) TransitionTask(ctx context.Context, arg TransitionTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, transitionTask, arg.ID, arg.Status, arg.Version)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
