// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on, required)
VALUES ($1, $2, $3)
`

type AddTaskDependencyParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	DependsOn pgtype.UUID `json:"depends_on"`
	Required  bool        `json:"required"`
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, addTaskDependency, arg.TaskID, arg.DependsOn, arg.Required)
	return err
}

const createAgentInstance = `-- name: CreateAgentInstance :one
WITH active_run AS (
    SELECT runs.id
    FROM runs
    WHERE runs.id = $1
      AND runs.status NOT IN ('cancelled', 'completed', 'budget_exhausted')
    FOR SHARE
)
INSERT INTO agent_instances (run_id, task_id, profile, status)
SELECT active_run.id, $2, $3, $4
FROM active_run
RETURNING id, run_id, task_id, profile, status, version, created_at, updated_at
`

type CreateAgentInstanceParams struct {
	ID      pgtype.UUID `json:"id"`
	TaskID  pgtype.UUID `json:"task_id"`
	Profile string      `json:"profile"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateAgentInstance(ctx context.Context, arg CreateAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, createAgentInstance,
		arg.ID,
		arg.TaskID,
		arg.Profile,
		arg.Status,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrGetRun = `-- name: CreateOrGetRun :one
INSERT INTO runs (project_id, scope_id, name, status, created_by, request_key, request_fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, created_by, request_key) WHERE request_key <> ''
DO UPDATE SET request_key = EXCLUDED.request_key
RETURNING id, project_id, scope_id, name, status, version, created_by, request_key, request_fingerprint, created_at, updated_at, (xmax = 0) AS created
`

type CreateOrGetRunParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	ScopeID            pgtype.UUID `json:"scope_id"`
	Name               string      `json:"name"`
	Status             string      `json:"status"`
	CreatedBy          string      `json:"created_by"`
	RequestKey         string      `json:"request_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
}

type CreateOrGetRunRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ScopeID            pgtype.UUID        `json:"scope_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedBy          string             `json:"created_by"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Created            bool               `json:"created"`
}

func (q *Queries) CreateOrGetRun(ctx context.Context, arg CreateOrGetRunParams) (CreateOrGetRunRow, error) {
	row := q.db.QueryRow(ctx, createOrGetRun,
		arg.ProjectID,
		arg.ScopeID,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
		arg.RequestKey,
		arg.RequestFingerprint,
	)
	var i CreateOrGetRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScopeID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, scope_id, name, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, scope_id, name, status, version, created_by, request_key, request_fingerprint, created_at, updated_at
`

type CreateRunParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Name      string      `json:"name"`
	Status    string      `json:"status"`
	CreatedBy string      `json:"created_by"`
}

type CreateRunRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ScopeID            pgtype.UUID        `json:"scope_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedBy          string             `json:"created_by"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.ScopeID,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
	)
	var i CreateRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScopeID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
WITH active_run AS (
    SELECT runs.id
    FROM runs
    WHERE runs.id = $1
      AND runs.status NOT IN ('cancelled', 'completed', 'budget_exhausted')
    FOR SHARE
)
INSERT INTO tasks (run_id, name, status)
SELECT active_run.id, $2, $3
FROM active_run
RETURNING id, run_id, name, status, version, created_at, updated_at
`

type CreateTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Status string      `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.ID, arg.Name, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentInstance = `-- name: GetAgentInstance :one
SELECT id, run_id, task_id, profile, status, version, created_at, updated_at
FROM agent_instances
WHERE id = $1
`

func (q *Queries) GetAgentInstance(ctx context.Context, id pgtype.UUID) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstance, id)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, scope_id, name, status, version, created_by, request_key, request_fingerprint, created_at, updated_at
FROM runs
WHERE id = $1
`

type GetRunRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ScopeID            pgtype.UUID        `json:"scope_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedBy          string             `json:"created_by"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScopeID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, run_id, name, status, version, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentInstancesByRun = `-- name: ListAgentInstancesByRun :many
SELECT id, run_id, task_id, profile, status, version, created_at, updated_at
FROM agent_instances
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentInstancesByRun(ctx context.Context, runID pgtype.UUID) ([]AgentInstance, error) {
	rows, err := q.db.Query(ctx, listAgentInstancesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstance
	for rows.Next() {
		var i AgentInstance
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TaskID,
			&i.Profile,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, scope_id, name, status, version, created_by, request_key, request_fingerprint, created_at, updated_at
FROM runs
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListRunsByProjectRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ScopeID            pgtype.UUID        `json:"scope_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedBy          string             `json:"created_by"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListRunsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByProjectRow
	for rows.Next() {
		var i ListRunsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScopeID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.RequestKey,
			&i.RequestFingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDependencies = `-- name: ListTaskDependencies :many
SELECT task_id, depends_on, required
FROM task_dependencies
WHERE task_id = $1
`

func (q *Queries) ListTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDependency
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(&i.TaskID, &i.DependsOn, &i.Required); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByRun = `-- name: ListTasksByRun :many
SELECT id, run_id, name, status, version, created_at, updated_at
FROM tasks
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTasksByRun(ctx context.Context, runID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionAgentInstance = `-- name: TransitionAgentInstance :one
UPDATE agent_instances
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, run_id, task_id, profile, status, version, created_at, updated_at
`

type TransitionAgentInstanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

func (q *Queries) TransitionAgentInstance(ctx context.Context, arg TransitionAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, transitionAgentInstance, arg.ID, arg.Status, arg.Version)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Profile,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionRun = `-- name: TransitionRun :one
UPDATE runs
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, project_id, scope_id, name, status, version, created_by, request_key, request_fingerprint, created_at, updated_at
`

type TransitionRunParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

type TransitionRunRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ScopeID            pgtype.UUID        `json:"scope_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedBy          string             `json:"created_by"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) TransitionRun(ctx context.Context, arg TransitionRunParams) (TransitionRunRow, error) {
	row := q.db.QueryRow(ctx, transitionRun, arg.ID, arg.Status, arg.Version)
	var i TransitionRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScopeID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.RequestKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionTask = `-- name: TransitionTask :one
UPDATE tasks
SET status = $2, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, run_id, name, status, version, created_at, updated_at
`

type TransitionTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Version int32       `json:"version"`
}

func (q *Queries) TransitionTask(ctx context.Context, arg TransitionTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, transitionTask, arg.ID, arg.Status, arg.Version)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
