// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (run_id, title, description, severity, confidence, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, title, description, severity, confidence, status, version, created_at, updated_at
`

type CreateFindingParams struct {
	RunID       pgtype.UUID `json:"run_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Severity    string      `json:"severity"`
	Confidence  string      `json:"confidence"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.RunID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Confidence,
		arg.Status,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinding = `-- name: GetFinding :one
SELECT id, run_id, title, description, severity, confidence, status, version, created_at, updated_at
FROM findings
WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id pgtype.UUID) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVerdict = `-- name: InsertVerdict :one
INSERT INTO finding_verdicts (finding_id, verdict, reason, produced_by)
VALUES ($1, $2, $3, $4)
RETURNING id, finding_id, verdict, reason, produced_by, created_at
`

type InsertVerdictParams struct {
	FindingID  pgtype.UUID `json:"finding_id"`
	Verdict    string      `json:"verdict"`
	Reason     string      `json:"reason"`
	ProducedBy string      `json:"produced_by"`
}

func (q *Queries) InsertVerdict(ctx context.Context, arg InsertVerdictParams) (FindingVerdict, error) {
	row := q.db.QueryRow(ctx, insertVerdict,
		arg.FindingID,
		arg.Verdict,
		arg.Reason,
		arg.ProducedBy,
	)
	var i FindingVerdict
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Verdict,
		&i.Reason,
		&i.ProducedBy,
		&i.CreatedAt,
	)
	return i, err
}

const linkFindingEvidence = `-- name: LinkFindingEvidence :exec
INSERT INTO finding_evidence (finding_id, evidence_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (finding_id, evidence_id) DO UPDATE SET role = EXCLUDED.role
`

type LinkFindingEvidenceParams struct {
	FindingID  pgtype.UUID `json:"finding_id"`
	EvidenceID pgtype.UUID `json:"evidence_id"`
	Role       string      `json:"role"`
}

func (q *Queries) LinkFindingEvidence(ctx context.Context, arg LinkFindingEvidenceParams) error {
	_, err := q.db.Exec(ctx, linkFindingEvidence, arg.FindingID, arg.EvidenceID, arg.Role)
	return err
}

const listFindingsByRun = `-- name: ListFindingsByRun :many
SELECT id, run_id, title, description, severity, confidence, status, version, created_at, updated_at
FROM findings
WHERE run_id = $1
ORDER BY created_at
`

func (q *Queries) ListFindingsByRun(ctx context.Context, runID pgtype.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.Confidence,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewHistory = `-- name: ListReviewHistory :many
SELECT id, finding_id, from_status, to_status, reviewer, reason, created_at
FROM finding_review_history
WHERE finding_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListReviewHistory(ctx context.Context, findingID pgtype.UUID) ([]FindingReviewHistory, error) {
	rows, err := q.db.Query(ctx, listReviewHistory, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindingReviewHistory
	for rows.Next() {
		var i FindingReviewHistory
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reviewer,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerdictsByFinding = `-- name: ListVerdictsByFinding :many
SELECT id, finding_id, verdict, reason, produced_by, created_at
FROM finding_verdicts
WHERE finding_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListVerdictsByFinding(ctx context.Context, findingID pgtype.UUID) ([]FindingVerdict, error) {
	rows, err := q.db.Query(ctx, listVerdictsByFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindingVerdict
	for rows.Next() {
		var i FindingVerdict
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Verdict,
			&i.Reason,
			&i.ProducedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionFindingWithHistory = `-- name: TransitionFindingWithHistory :one
WITH prev AS (
    SELECT findings.id, findings.status
    FROM findings
    WHERE findings.id = $1 AND findings.version = $3
),
updated AS (
    UPDATE findings
    SET status = $2, version = findings.version + 1, updated_at = now()
    WHERE findings.id = $1 AND findings.version = $3
    RETURNING findings.id, findings.run_id, findings.title, findings.description, findings.severity, findings.confidence, findings.status, findings.version, findings.created_at, findings.updated_at
),
inserted AS (
    INSERT INTO finding_review_history (finding_id, from_status, to_status, reviewer, reason)
    SELECT u.id, p.status, u.status, $4, $5
    FROM updated u JOIN prev p ON p.id = u.id
)
SELECT u.id, u.run_id, u.title, u.description, u.severity, u.confidence, u.status, u.version, u.created_at, u.updated_at
FROM updated u
`

type TransitionFindingWithHistoryParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Version  int32       `json:"version"`
	Reviewer string      `json:"reviewer"`
	Reason   string      `json:"reason"`
}

type TransitionFindingWithHistoryRow struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	Confidence  string             `json:"confidence"`
	Status      string             `json:"status"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Atomically applies a finding status transition and records its review
// history in a single statement. from_status is read from the very row being
// updated (not supplied by the caller), so the history can never disagree with
// the pre-image. A stale version produces no updated row (optimistic lock) and
// therefore no history row.
func (q *Queries) TransitionFindingWithHistory(ctx context.Context, arg TransitionFindingWithHistoryParams) (TransitionFindingWithHistoryRow, error) {
	row := q.db.QueryRow(ctx, transitionFindingWithHistory,
		arg.ID,
		arg.Status,
		arg.Version,
		arg.Reviewer,
		arg.Reason,
	)
	var i TransitionFindingWithHistoryRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
