// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error)
	CreateFindingRevision(ctx context.Context, arg CreateFindingRevisionParams) (FindingRevision, error)
	CreateReviewHistory(ctx context.Context, arg CreateReviewHistoryParams) error
	DeleteFindingEvidence(ctx context.Context, findingID pgtype.UUID) error
	GetCurrentFindingRevision(ctx context.Context, findingID pgtype.UUID) (FindingRevision, error)
	GetFinding(ctx context.Context, id pgtype.UUID) (Finding, error)
	GetFindingRevision(ctx context.Context, arg GetFindingRevisionParams) (FindingRevision, error)
	InsertFindingEvidence(ctx context.Context, arg InsertFindingEvidenceParams) error
	InsertVerdict(ctx context.Context, arg InsertVerdictParams) (InsertVerdictRow, error)
	ListFindingRevisionEvidence(ctx context.Context, arg ListFindingRevisionEvidenceParams) ([]ListFindingRevisionEvidenceRow, error)
	ListFindingRevisions(ctx context.Context, findingID pgtype.UUID) ([]FindingRevision, error)
	ListFindingsByRun(ctx context.Context, runID pgtype.UUID) ([]Finding, error)
	ListReviewHistory(ctx context.Context, findingID pgtype.UUID) ([]ListReviewHistoryRow, error)
	ListVerdictsByFinding(ctx context.Context, findingID pgtype.UUID) ([]ListVerdictsByFindingRow, error)
	NextFindingRevisionNo(ctx context.Context, findingID pgtype.UUID) (int32, error)
	SnapshotFindingEvidence(ctx context.Context, arg SnapshotFindingEvidenceParams) error
	UpdateFindingContent(ctx context.Context, arg UpdateFindingContentParams) (Finding, error)
	UpdateFindingStatus(ctx context.Context, arg UpdateFindingStatusParams) (Finding, error)
}

var _ Querier = (*Queries)(nil)
