// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error)
	GetFinding(ctx context.Context, id pgtype.UUID) (Finding, error)
	InsertVerdict(ctx context.Context, arg InsertVerdictParams) (FindingVerdict, error)
	LinkFindingEvidence(ctx context.Context, arg LinkFindingEvidenceParams) error
	ListFindingsByRun(ctx context.Context, runID pgtype.UUID) ([]Finding, error)
	ListReviewHistory(ctx context.Context, findingID pgtype.UUID) ([]FindingReviewHistory, error)
	ListVerdictsByFinding(ctx context.Context, findingID pgtype.UUID) ([]FindingVerdict, error)
	// Atomically applies a finding status transition and records its review
	// history in a single statement. from_status is read from the very row being
	// updated (not supplied by the caller), so the history can never disagree with
	// the pre-image. A stale version produces no updated row (optimistic lock) and
	// therefore no history row.
	TransitionFindingWithHistory(ctx context.Context, arg TransitionFindingWithHistoryParams) (TransitionFindingWithHistoryRow, error)
}

var _ Querier = (*Queries)(nil)
