// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelReport(ctx context.Context, arg CancelReportParams) (ReportRequest, error)
	ClaimReport(ctx context.Context, arg ClaimReportParams) (ReportRequest, error)
	CompleteReport(ctx context.Context, arg CompleteReportParams) (ReportRequest, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error)
	FailReport(ctx context.Context, arg FailReportParams) (ReportRequest, error)
	GetReport(ctx context.Context, id pgtype.UUID) (ReportRequest, error)
	GetReportByRun(ctx context.Context, runID pgtype.UUID) (ReportRequest, error)
}

var _ Querier = (*Queries)(nil)
