// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReport = `-- name: CancelReport :one
UPDATE report_requests
SET status = 'cancelled',
    lease_owner = NULL,
    lease_expires_at = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND status IN ('queued', 'rendering')
RETURNING id, run_id, template_id, template_version, template_hash, snapshot,
          status, version, lease_owner, lease_expires_at, output_artifact_id,
          failure_code, failure_message, created_at, updated_at
`

type CancelReportParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) CancelReport(ctx context.Context, arg CancelReportParams) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, cancelReport, arg.ID, arg.Version)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimReport = `-- name: ClaimReport :one
UPDATE report_requests
SET status = 'rendering',
    lease_owner = $2,
    lease_expires_at = now() + ($3::bigint * interval '1 microsecond'),
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $4
  AND (
      status = 'queued'
      OR (status = 'rendering' AND lease_expires_at <= now())
  )
RETURNING id, run_id, template_id, template_version, template_hash, snapshot,
          status, version, lease_owner, lease_expires_at, output_artifact_id,
          failure_code, failure_message, created_at, updated_at
`

type ClaimReportParams struct {
	ID         pgtype.UUID `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
	Column3    int64       `json:"column_3"`
	Version    int32       `json:"version"`
}

func (q *Queries) ClaimReport(ctx context.Context, arg ClaimReportParams) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, claimReport,
		arg.ID,
		arg.LeaseOwner,
		arg.Column3,
		arg.Version,
	)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeReport = `-- name: CompleteReport :one
UPDATE report_requests
SET status = 'completed',
    lease_owner = NULL,
    lease_expires_at = NULL,
    output_artifact_id = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND status = 'rendering'
  AND lease_owner = $4
  AND lease_expires_at > now()
  AND output_artifact_id IS NULL
RETURNING id, run_id, template_id, template_version, template_hash, snapshot,
          status, version, lease_owner, lease_expires_at, output_artifact_id,
          failure_code, failure_message, created_at, updated_at
`

type CompleteReportParams struct {
	ID               pgtype.UUID `json:"id"`
	Version          int32       `json:"version"`
	OutputArtifactID pgtype.UUID `json:"output_artifact_id"`
	LeaseOwner       pgtype.Text `json:"lease_owner"`
}

func (q *Queries) CompleteReport(ctx context.Context, arg CompleteReportParams) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, completeReport,
		arg.ID,
		arg.Version,
		arg.OutputArtifactID,
		arg.LeaseOwner,
	)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO report_requests (
    run_id, template_id, template_version, template_hash, snapshot, status
)
VALUES ($1, $2, $3, $4, $5, 'queued')
ON CONFLICT (run_id) DO UPDATE
SET run_id = EXCLUDED.run_id
RETURNING id, run_id, template_id, template_version, template_hash, snapshot,
          status, version, lease_owner, lease_expires_at, output_artifact_id,
          failure_code, failure_message, created_at, updated_at, (xmax = 0) AS created
`

type CreateReportParams struct {
	RunID           pgtype.UUID `json:"run_id"`
	TemplateID      string      `json:"template_id"`
	TemplateVersion string      `json:"template_version"`
	TemplateHash    string      `json:"template_hash"`
	Snapshot        []byte      `json:"snapshot"`
}

type CreateReportRow struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	TemplateID       string             `json:"template_id"`
	TemplateVersion  string             `json:"template_version"`
	TemplateHash     string             `json:"template_hash"`
	Snapshot         []byte             `json:"snapshot"`
	Status           string             `json:"status"`
	Version          int32              `json:"version"`
	LeaseOwner       pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	OutputArtifactID pgtype.UUID        `json:"output_artifact_id"`
	FailureCode      string             `json:"failure_code"`
	FailureMessage   string             `json:"failure_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Created          bool               `json:"created"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.RunID,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.TemplateHash,
		arg.Snapshot,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}

const failReport = `-- name: FailReport :one
UPDATE report_requests
SET status = 'failed',
    lease_owner = NULL,
    lease_expires_at = NULL,
    failure_code = $3,
    failure_message = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND status = 'rendering'
  AND lease_owner = $5
  AND lease_expires_at > now()
RETURNING id, run_id, template_id, template_version, template_hash, snapshot,
          status, version, lease_owner, lease_expires_at, output_artifact_id,
          failure_code, failure_message, created_at, updated_at
`

type FailReportParams struct {
	ID             pgtype.UUID `json:"id"`
	Version        int32       `json:"version"`
	FailureCode    string      `json:"failure_code"`
	FailureMessage string      `json:"failure_message"`
	LeaseOwner     pgtype.Text `json:"lease_owner"`
}

func (q *Queries) FailReport(ctx context.Context, arg FailReportParams) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, failReport,
		arg.ID,
		arg.Version,
		arg.FailureCode,
		arg.FailureMessage,
		arg.LeaseOwner,
	)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, run_id, template_id, template_version, template_hash, snapshot,
       status, version, lease_owner, lease_expires_at, output_artifact_id,
       failure_code, failure_message, created_at, updated_at
FROM report_requests
WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id pgtype.UUID) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByRun = `-- name: GetReportByRun :one
SELECT id, run_id, template_id, template_version, template_hash, snapshot,
       status, version, lease_owner, lease_expires_at, output_artifact_id,
       failure_code, failure_message, created_at, updated_at
FROM report_requests
WHERE run_id = $1
`

func (q *Queries) GetReportByRun(ctx context.Context, runID pgtype.UUID) (ReportRequest, error) {
	row := q.db.QueryRow(ctx, getReportByRun, runID)
	var i ReportRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.TemplateHash,
		&i.Snapshot,
		&i.Status,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.OutputArtifactID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
